# Generated by Django 5.2.1 on 2025-07-21 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspost',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='newspost',
            name='youtube_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
