# Generated by Django 5.2.1 on 2025-07-17 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trials', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trialevent',
            old_name='date',
            new_name='start_date',
        ),
        migrations.AddField(
            model_name='trialevent',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trialevent',
            name='register_fees',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
