# Generated by Django 5.2.1 on 2025-07-23 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trials', '0002_rename_date_trialevent_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trialregistration',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trialregistration',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
