# Generated by Django 5.2.1 on 2025-06-02 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(max_length=10)),
                ('upi', models.CharField(editable=False, max_length=10, unique=True)),
                ('position', models.CharField(max_length=50)),
                ('profile_image', models.ImageField(upload_to='players/images/')),
                ('video', models.FileField(blank=True, null=True, upload_to='players/videos/')),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
