# Generated by Django 5.2.1 on 2025-07-17 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='name',
        ),
        migrations.AddField(
            model_name='player',
            name='first_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='surname',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
